Storybook components vol. 2
AndreyGorelik/VamostStorybook pull request #12
Opened 2023-08-22 09:37 UTC by AndreyGorelik

2023-08-22 11:54 UTC, HenoL-rgb approved these changes

2023-08-22 11:54 UTC, HenoL-rgb commented on src/shared/ui/userpicGallery/userPicGallery.styles.ts
> +    borderColor: 'white',
color

2023-08-23 14:39 UTC, PetrifiedEye requested changes

2023-08-23 14:39 UTC, PetrifiedEye commented on src/shared/ui/postFullHost/postFullHost.types.ts
> +  post_tags: PostTag[];
Suggest to change names here

2023-08-23 14:39 UTC, PetrifiedEye commented on src/shared/ui/selectList/selectList.styles.ts
There's no styles, thus it's better to remove that file

2023-08-23 14:39 UTC, PetrifiedEye commented on src/utils/convertTime/convertTime.ts
Same here

2023-08-24 12:50 UTC, PetrifiedEye approved these changes

2023-08-24 12:55 UTC, merged