Post create with back
AndreyGorelik/VamostStorybook pull request #31
Opened 2023-09-15 11:06 UTC by AndreyGorelik

2023-09-20 13:06 UTC, HenoL-rgb requested changes

2023-09-20 13:06 UTC, HenoL-rgb commented on src/shared/ui/postCreate/postCreate.component.tsx
> +    newPost.gender = ['Man'];
get gender from users showGender props

2023-09-25 13:43 UTC, PetrifiedEye requested changes

2023-09-25 13:43 UTC, PetrifiedEye commented on src/shared/ui/tagList/tagList.component.tsx
> +          <Text>{item.label.charAt(0).toUpperCase() + item.label.slice(1)}</Text>
try
``` 
textStye: {
    textTransform: 'capitalize'
}
```

2023-09-26 13:45 UTC, merged